import type Stripe from 'stripe';

/**
 * Mock Stripe Customer for testing
 */
export const mockStripeCustomer: Stripe.Customer = {
  id: 'cus_test123',
  object: 'customer',
  email: 'test@example.com',
  name: 'Test Organization',
  metadata: {
    org_id: 'test-org-id',
    owner_id: 'test-user-id',
  },
  created: Math.floor(Date.now() / 1000),
  livemode: false,
  address: null,
  balance: 0,
  currency: null,
  default_source: null,
  delinquent: false,
  description: null,
  discount: null,
  invoice_prefix: null,
  invoice_settings: {
    custom_fields: null,
    default_payment_method: null,
    footer: null,
    rendering_options: null,
  },
  phone: null,
  preferred_locales: [],
  shipping: null,
  tax_exempt: 'none',
  test_clock: null,
};

/**
 * Mock Stripe Checkout Session for testing
 */
export const mockStripeCheckoutSession: Stripe.Checkout.Session = {
  id: 'cs_test123',
  object: 'checkout.session',
  customer: 'cus_test123',
  mode: 'subscription',
  status: 'complete',
  url: 'https://checkout.stripe.com/test',
  success_url: 'http://localhost:3000/billing/success',
  cancel_url: 'http://localhost:3000/billing?canceled=true',
  metadata: {
    org_id: 'test-org-id',
    user_id: 'test-user-id',
  },
  currency_conversion: null,
  created: Math.floor(Date.now() / 1000),
  livemode: false,
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 2900,
  amount_total: 2900,
  automatic_tax: {
    enabled: false,
    liability: null,
    status: null,
  },
  billing_address_collection: null,
  client_reference_id: null,
  client_secret: null,
  consent: null,
  consent_collection: null,
  currency: 'usd',
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer_creation: null,
  customer_details: null,
  customer_email: null,
  expires_at: Math.floor(Date.now() / 1000) + 86400,
  invoice: null,
  invoice_creation: null,
  line_items: undefined,
  locale: null,
  payment_intent: null,
  payment_link: null,
  payment_method_collection: null,
  payment_method_configuration_details: null,
  payment_method_options: null,
  payment_method_types: ['card'],
  payment_status: 'paid',
  phone_number_collection: { enabled: false },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_details: null,
  shipping_options: [],
  submit_type: null,
  subscription: 'sub_test123',
  tax_id_collection: { enabled: false },
  total_details: null,
  ui_mode: 'hosted',
};

/**
 * Mock Stripe Subscription for testing
 */
export const mockStripeSubscription: Stripe.Subscription = {
  id: 'sub_test123',
  object: 'subscription',
  customer: 'cus_test123',
  status: 'active',
  discounts: [],
  items: {
    object: 'list',
    data: [
      {
        id: 'si_test123',
        object: 'subscription_item',
        discounts: [],
        price: {
          id: 'price_pro_monthly',
          object: 'price',
          active: true,
          billing_scheme: 'per_unit',
          created: Math.floor(Date.now() / 1000),
          currency: 'usd',
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: 'prod_test123',
          recurring: {
            aggregate_usage: null,
            interval: 'month',
            interval_count: 1,
            meter: null,
            trial_period_days: null,
            usage_type: 'licensed',
          },
          tax_behavior: 'unspecified',
          tiers_mode: null,
          transform_quantity: null,
          type: 'recurring',
          unit_amount: 2900,
          unit_amount_decimal: '2900',
        },
        quantity: 1,
        billing_thresholds: null,
        created: Math.floor(Date.now() / 1000),
        metadata: {},
        plan: {
          id: 'price_pro_monthly',
          object: 'plan',
          active: true,
          aggregate_usage: null,
          amount: 2900,
          amount_decimal: '2900',
          billing_scheme: 'per_unit',
          created: Math.floor(Date.now() / 1000),
          currency: 'usd',
          interval: 'month',
          interval_count: 1,
          livemode: false,
          metadata: {},
          meter: null,
          nickname: null,
          product: 'prod_test123',
          tiers_mode: null,
          transform_usage: null,
          trial_period_days: null,
          usage_type: 'licensed',
        },
        subscription: 'sub_test123',
        tax_rates: [],
      },
    ],
    has_more: false,
    url: '/v1/subscription_items',
  },
  current_period_start: Math.floor(Date.now() / 1000),
  current_period_end: Math.floor(Date.now() / 1000) + 30 * 24 * 60 * 60,
  cancel_at_period_end: false,
  metadata: {
    org_id: 'test-org-id',
  },
  created: Math.floor(Date.now() / 1000),
  livemode: false,
  application: null,
  application_fee_percent: null,
  automatic_tax: {
    enabled: false,
    liability: null,
  },
  billing_cycle_anchor: Math.floor(Date.now() / 1000),
  billing_cycle_anchor_config: null,
  billing_thresholds: null,
  cancel_at: null,
  canceled_at: null,
  cancellation_details: null,
  collection_method: 'charge_automatically',
  currency: 'usd',
  days_until_due: null,
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  ended_at: null,
  latest_invoice: null,
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: null,
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  schedule: null,
  start_date: Math.floor(Date.now() / 1000),
  test_clock: null,
  transfer_data: null,
  trial_end: null,
  trial_settings: null,
  trial_start: null,
};

/**
 * Mock Stripe Invoice for testing
 */
export const mockStripeInvoice: Stripe.Invoice = {
  id: 'in_test123',
  object: 'invoice',
  customer: 'cus_test123',
  subscription: 'sub_test123',
  subscription_details: { metadata: {} },
  status: 'paid',
  amount_paid: 2900,
  amount_due: 2900,
  currency: 'usd',
  customer_email: 'test@example.com',
  hosted_invoice_url: 'https://invoice.stripe.com/test',
  invoice_pdf: 'https://invoice.stripe.com/test.pdf',
  period_start: Math.floor(Date.now() / 1000),
  period_end: Math.floor(Date.now() / 1000) + 30 * 24 * 60 * 60,
  status_transitions: {
    paid_at: Math.floor(Date.now() / 1000),
    finalized_at: Math.floor(Date.now() / 1000),
    marked_uncollectible_at: null,
    voided_at: null,
  },
  created: Math.floor(Date.now() / 1000),
  livemode: false,
  account_country: 'US',
  account_name: 'Test Account',
  account_tax_ids: null,
  amount_remaining: 0,
  amount_shipping: 0,
  application: null,
  application_fee_amount: null,
  attempt_count: 1,
  attempted: true,
  auto_advance: true,
  automatic_tax: {
    enabled: false,
    liability: null,
    status: null,
  },
  billing_reason: 'subscription_cycle',
  charge: 'ch_test123',
  collection_method: 'charge_automatically',
  custom_fields: null,
  customer_address: null,
  customer_name: null,
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: 'none',
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  discounts: [],
  due_date: null,
  effective_at: null,
  ending_balance: 0,
  footer: null,
  from_invoice: null,
  issuer: {
    type: 'self',
  },
  last_finalization_error: null,
  latest_revision: null,
  lines: {
    object: 'list',
    data: [],
    has_more: false,
    url: '/v1/invoices/in_test123/lines',
  },
  metadata: {},
  next_payment_attempt: null,
  number: 'TEST-0001',
  on_behalf_of: null,
  paid: true,
  paid_out_of_band: false,
  payment_intent: null,
  payment_settings: {
    default_mandate: null,
    payment_method_options: null,
    payment_method_types: null,
  },
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  quote: null,
  receipt_number: null,
  rendering: null,
  rendering_options: null,
  shipping_cost: null,
  shipping_details: null,
  starting_balance: 0,
  statement_descriptor: null,
  subtotal: 2900,
  subtotal_excluding_tax: null,
  tax: null,
  test_clock: null,
  threshold_reason: undefined,
  total: 2900,
  total_discount_amounts: [],
  total_excluding_tax: null,
  total_tax_amounts: [],
  transfer_data: null,
  webhooks_delivered_at: null,
};

/**
 * Factory function to create mock Stripe events
 */
export function createMockStripeEvent<T>(type: string, data: T): Stripe.Event {
  return {
    id: `evt_test_${Date.now()}`,
    object: 'event',
    type,
    data: {
      object: data,
      previous_attributes: undefined,
    },
    created: Math.floor(Date.now() / 1000),
    livemode: false,
    api_version: '2024-11-20.acacia',
    pending_webhooks: 0,
    request: null,
  } as Stripe.Event;
}
